<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260206085527 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE contact (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, phone VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, surname VARCHAR(255) NOT NULL, birthday DATE NOT NULL, contact_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7A1254A ON "user" (contact_id)');
        $this->addSql('CREATE TABLE work_experiences (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, company VARCHAR(255) NOT NULL, position VARCHAR(255) NOT NULL, date_from DATE NOT NULL, date_to DATE NOT NULL, profile_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9DC3EEB3CCFA12B8 ON work_experiences (profile_id)');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649E7A1254A FOREIGN KEY (contact_id) REFERENCES contact (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE work_experiences ADD CONSTRAINT FK_9DC3EEB3CCFA12B8 FOREIGN KEY (profile_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649E7A1254A');
        $this->addSql('ALTER TABLE work_experiences DROP CONSTRAINT FK_9DC3EEB3CCFA12B8');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE work_experiences');
    }
}
